Feature: JSONPlaceholder Posts API

  Background:
    * url 'https://jsonplaceholder.typicode.com'

  Scenario: GET /posts returns a non-empty list with correct schema
    Given path '/posts'
    When method GET
    Then status 200
    And match response == '#[]'
    And match response[0] == { userId: '#number', id: '#number', title: '#string', body: '#string' }
    And assert response.length == 100

  Scenario: POST /posts creates a resource
    Given path '/posts'
    And request { title: 'QualityHub', body: 'Testing with Karate', userId: 1 }
    When method POST
    Then status 201
    And match response.id == '#number'
    And match response.title == 'QualityHub'

  Scenario Outline: POST /posts with varied payloads
    Given path '/posts'
    And request { title: '<title>', body: '<body>', userId: <userId> }
    When method POST
    Then status 201
    And match response.title == '<title>'

    Examples:
      | title            | body                   | userId |
      | Unit test report | Generated by pipeline  | 1      |
      | Bug regression   | Fixed in v2.1          | 2      |
      | Smoke suite run  | All checks passed      | 3      |
